INSERT INTO `User_settings` (highlight_words,
            whois_username,
            whois_realname,
            global_nickname,
            show_joinpartquit_messages,
            show_seconds,
            show_video_previews,
            show_image_previews,
            Registred_users_userID) values("", "", "", "", "", "", "", "", "")
ON DUPLICATE KEY UPDATE highlight_words="",
						whois_username="",
						whois_realname="",
                        global_nickname="",
                        show_joinpartquit_messages="",
                        show_seconds="",
                        show_video_previews="",
                        show_image_previews="");
